name: ci
run-name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm

      - run: make compile
      - run: make lint
      - run: make test
